CREATE DATABASE PIZZASALES;
USE PIZZASALES;
CREATE TABLE pizza_sales ( sale_id INT AUTO_INCREMENT PRIMARY KEY,
 sale_date DATE, 
 pizza_type VARCHAR(50), 
 size VARCHAR(20), 
 quantity INT, 
 price DECIMAL(10, 2),
 location VARCHAR(50) );
INSERT INTO pizza_sales (sale_date, pizza_type, size, quantity, price, location)
VALUES
('2024-01-01', 'Pepperoni', 'Small', 5, 8.99, 'New York'), 
('2024-01-01', 'Pepperoni', 'Medium', 3, 12.99, 'New York'), 
('2024-01-02', 'Margherita', 'Large', 2, 15.99, 'New York'), 
('2024-01-02', 'BBQ Chicken', 'Small', 4, 9.99, 'Chicago'), 
('2024-01-03', 'Vegetarian', 'Large', 6, 14.99, 'Los Angeles'), 
('2024-01-04', 'Pepperoni', 'Small', 7, 8.99, 'Chicago'),
('2024-01-05', 'BBQ Chicken', 'Medium', 2, 13.99, 'Los Angeles'), 
('2024-01-06', 'Margherita', 'Small', 8, 7.99, 'New York'), 
('2024-01-07', 'Vegetarian', 'Medium', 3, 12.99, 'Chicago'), 
('2024-01-08', 'Pepperoni', 'Large', 1, 15.99, 'Los Angeles'), 
('2024-01-09', 'BBQ Chicken', 'Large', 2, 17.99, 'New York'), 
('2024-01-10', 'Vegetarian', 'Small', 5, 9.99, 'Chicago');

SELECT * FROM PIZZA_SALES;
 

##QUREY 1
SELECT PIZZA_TYPE,SUM(QUANTITY*PRICE)'TOTAL SALES'
FROM PIZZA_SALES
GROUP BY PIZZA_TYPE;

##QUREY 2
SELECT PIZZA_TYPE,ROUND(AVG(PRICE))'AVERAGE_PRICE'
FROM PIZZA_SALES
GROUP BY PIZZA_TYPE;

##QUREY 3
SELECT LOCATION,
SUM(QUANTITY)
FROM PIZZA_SALES
GROUP BY LOCATION; 

DROP TABLE PIZZA_SALES;

##QUREY 4
SELECT SIZE,SUM(QUANTITY*PRICE)'TOTAL SLAES AMOUNT'
FROM PIZZA_SALES 
GROUP BY SIZE;

##QUREY 5
SELECT PIZZA_TYPE,SIZE,SUM(QUANTITY*PRICE)'TOTAL SLAES AMOUNT'
FROM PIZZA_SALES
GROUP BY PIZZA_TYPE,SIZE;

##QUREY 6
SELECT MONTH(SALE_DATE),SUM(QUANTITY*PRICE)'TOTAL SLAES AMOUNT'
FROM PIZZA_SALES
GROUP BY MONTH(SALE_DATE);


##QUREY 7
SELECT LOCATION,PIZZA_TYPE,SUM(QUANTITY*PRICE)'TOTAL SLAES AMOUNT'
FROM PIZZA_SALES
GROUP BY LOCATION,PIZZA_TYPE; 

##QUREY 8
SELECT PIZZA_TYPE,COUNT(*)
FROM PIZZA_SALES
GROUP BY PIZZA_TYPE
ORDER BY PIZZA_TYPE DESC;

##QUREY 9
SELECT 
    PIZZA_TYPE,SUM(QUANTITY*PRICE),
    CASE
        WHEN SUM(QUANTITY * PRICE) BETWEEN 0 AND 100 THEN 'LOW'
        WHEN SUM(QUANTITY * PRICE) BETWEEN 101 AND 150 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SALES_CATEGORY
FROM
    PIZZA_SALES
GROUP BY PIZZA_TYPE
ORDER BY PIZZA_TYPE; 

##QUREY 10
SELECT 
    PIZZA_TYPE,SIZE,QUANTITY,SUM(QUANTITY*PRICE)'TOTAL SALES'
FROM
    pizza_sales
GROUP BY PIZZA_TYPE,SIZE,quantity
HAVING SUM(QUANTITY) >= 5;

##QUERY 11
SELECT SIZE,LOCATION,SUM(PRICE)'TOTAL SALES'
FROM PIZZA_SALES
GROUP BY SIZE,LOCATION
ORDER BY SIZE,LOCATION DESC;

##QUERY 12
SELECT PIZZA_TYPE,ROUND(AVG(QUANTITY))'AVERAGE SALE'
FROM PIZZA_SALES
GROUP BY PIZZA_TYPE
ORDER BY PIZZA_TYPE;

##QUERY 13
SELECT 
    LOCATION,SUM(PRICE)'TOTAL SALES',
    ROUND(AVG(PRICE)) 'AVERAGE SALES',
    CASE
        WHEN ROUND(AVG(PRICE)) >= 10 THEN 'HIGH'
        ELSE 'LOW'
    END AS AVERAGEPRICE
FROM
    PIZZA_SALES
GROUP BY LOCATION; 

 ##QUERY 14
SELECT 
    dayname(SALE_DATE),SUM(QUANTITY*PRICE)'TOTAL SALES'
FROM
    PIZZA_SALES
GROUP BY dayname(SALE_DATE);

##QUERY 15
SELECT MONTH(SALE_DATE),LOCATION,SUM(PRICE)'TOTAL SALES'
FROM PIZZA_SALES
GROUP BY MONTH(SALE_DATE),LOCATION;

##QUERY 16
SELECT 
    PIZZA_TYPE,
    CASE
        WHEN SUM(PRICE) < 10 THEN 'LOW'
        WHEN SUM(PRICE) BETWEEN 10 AND 15 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SALECATEGORY
FROM
    PIZZA_SALES
GROUP BY PIZZA_TYPE;

##QUERY 17
SELECT 
    LOCATION, SUM(QUANTITY * PRICE)
FROM
    PIZZA_SALES
GROUP BY LOCATION
HAVING SUM(QUANTITY * PRICE) >= 100;


##QUERY 18
SELECT 
    PIZZA_TYPE, ROUND(AVG(QUANTITY)) 'AVERAGESALES'
FROM
    PIZZA_SALES
GROUP BY PIZZA_TYPE
ORDER BY PIZZA_TYPE;

##QUERY 19
SELECT 
    DAYNAME(SALE_DATE),
    LOCATION,
    SUM(QUANTITY * PRICE) 'TOTALSALES'
FROM
    PIZZA_SALES
GROUP BY DAYNAME(SALE_DATE) , LOCATION;
